# MongoExpress - Development Tools
version: '3.8'

# Service definition
services:
  mongoExpress:
    image: mongo-express:0.54.0
    container_name: mongoexpress
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.102
    ports:
      - "5002:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "192.168.2.11"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "mongo"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "pirloKAKA88"
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
