# PGAdmin - Development Tools
version: '3.8'

# Service definition
services:
  pgAdmin:
    image: dpage/pgadmin4:${PG_ADMIN_TAG}
    container_name: pgadmin
    volumes: 
      - pgAdminVolume:/var/lib/pgadmin4/storage
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.200
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

# Volume definition 
volumes:
  pgAdminVolume: 
    name: pgadminVolume


