- hosts: all
  become: yes
  remote_user: "{{ ansible_user }}"
  vars_files:
    - ~/ansible/vars_ubuntu.yml
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist

    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg-agent

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        group: docker

    - name: Check docker-compose exists
      stat:
        path: /usr/local/bin/docker-compose
      register: docker_compose_exists

    - name: Download docker-compose {{ docker_compose_version }}
      get_url:
        url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
      when: not docker_compose_exists.stat.exists

    - name: Copying docker compose files and vaults
      copy:
        src: ../vars
        dest: /home/{{ ansible_user }}
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: 0755

    - name: Sourcing environment variables
      shell: |
        source /home/{{ ansible_user }}/vars/vaults/envvars
      args:
        executable: /bin/bash

    - name: Run compose file(s)
      shell: |
        cd /home/{{ ansible_user }}/vars/composes/{{ item }}

        cp /home/{{ ansible_user }}/vars/vaults/.env ./

        docker-compose up -d
      with_items:
        - postgresql
        - pgadmin