# PGAdmin - Development Tools
version: '3.8'

# Service definition
services:
  pgAdmin:
    image: dpage/pgadmin4:4.29
    container_name: pgAdmin
    volumes: 
      - pgAdminVolume:/var/lib/pgadmin4/storage
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.200
    ports:
      - "6000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "unis.badri@elementcreativestudio.com"
      PGADMIN_DEFAULT_PASSWORD: "pirloKAKA88"
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

# Volume definition 
volumes:
  pgAdminVolume: 
    name: pgadminVolume


